// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3BHUvECgW9KYGERYHQCnA-_vgUWk8II',
    appId: '1:489110133030:web:c42d7e54f10fdf01d089e7',
    messagingSenderId: '489110133030',
    projectId: 'dinorun-58272',
    authDomain: 'dinorun-58272.firebaseapp.com',
    storageBucket: 'dinorun-58272.firebasestorage.app',
    measurementId: 'G-RKGG3S64V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GSwVCKBEjkZ1R4uuUvYLRVv1eRwY8Ts',
    appId: '1:489110133030:android:ae51cd795f389f58d089e7',
    messagingSenderId: '489110133030',
    projectId: 'dinorun-58272',
    storageBucket: 'dinorun-58272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXYRbT5UiOSK7h2fMjSANLyty99WagCTw',
    appId: '1:489110133030:ios:c14a57eed6ef048fd089e7',
    messagingSenderId: '489110133030',
    projectId: 'dinorun-58272',
    storageBucket: 'dinorun-58272.firebasestorage.app',
    iosBundleId: 'com.example.fossilRush',
  );
}
